version: 0.1

#environment_variables:
#  plaintext:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - ./build/0.install.sh
  pre_build:
    commands:
      - ./build/1.prebuild.sh
  build:
    commands:
      - ./build/2.build.sh
#  post_build:
#    commands:
      # TODO acceptance tests
      # TODO (In a different project) integration tests
      # TODO (In a different project?) performance tests
#artifacts:
#  files:
#    - .travis.yml # a useless but small file to satisfy the buildspec.yml requirement
