version: 0.1

#environment_variables:
#  plaintext:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - echo $STAGE
      - echo `$STAGE`
      - npm install -q -g serverless
  pre_build:
    commands:
      - npm install -q
      - cd products/lambda && npm install -q
      - cd product-catalog && npm install -q
  build:
    commands:
      - npm run test
      - npm run lint
#      - cd build           && sls deploy -s $STAGE
      - cd retail-stream   && SLS_DEBUG=* && sls deploy -s $STAGE
      - cd products/lambda && sls deploy -s $STAGE
      - cd product-catalog && sls deploy -s $STAGE
  post_build:
    commands:
      # TODO acceptance tests
      # TODO (In a different project) integration tests
      # TODO (In a different project?) performance tests
#artifacts:
#  files:
#    - .travis.yml # a useless but small file to satisfy the buildspec.yml requirement
