version: 0.1

phases:
  install:
    commands:
      - printenv
      - echo
      - node --version
      - npm --version
      #- npm install -g serverless
      - npm install -g git+https://github.com/erikerikson/serverless.git#allow-self-reference

      - sls --version
      - echo
      # Is this up to date?
      - aws s3 sync s3://com.$COMPANY.$TEAM.serverless.$REGION/secrets/hello-retail . --region $REGION
      - ls -l
      - head -50 ./private.yml
      - echo
  pre_build:
    commands:
      - chmod 700 $CODEBUILD_SRC_DIR/build/1.install.sh
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Top-Level Project Dependencies"           $CODEBUILD_SRC_DIR
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing New Product Simulator Dependencies"       $CODEBUILD_SRC_DIR/product-creation/lambda
      # Product Catalog
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Catalog Dependencies"             $CODEBUILD_SRC_DIR/product-catalog/builder
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Catalog API"                      $CODEBUILD_SRC_DIR/product-catalog/api
      # Product Photos
      # TODO Update these accordingly with changes
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Photos - Execute Dependencies"    $CODEBUILD_SRC_DIR/product-photos/0.execute
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Photos - Message Dependencies"    $CODEBUILD_SRC_DIR/product-photos/2.message
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Photos - Receive Dependencies"    $CODEBUILD_SRC_DIR/product-photos/3.receive
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Photos - Unmessage Dependencies"  $CODEBUILD_SRC_DIR/product-photos/5.unmessage
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Photos - Report Dependencies"     $CODEBUILD_SRC_DIR/product-photos/6.report
  build:
    commands:
      - npm run test
      - npm run lint
      - chmod 700 $CODEBUILD_SRC_DIR/build/2.deploy.sh
      # Core Stream
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Retail Stream"                $CODEBUILD_SRC_DIR/retail-stream
      # Product Creation
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying New Products Simulator"       $CODEBUILD_SRC_DIR/product-creation/lambda
      # Product Catalog
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Catalog Processor"    $CODEBUILD_SRC_DIR/product-catalog/builder
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Catalog API"          $CODEBUILD_SRC_DIR/product-catalog/api
      # Product Photos
      # TODO Update these accordingly with changes
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - Data"        $CODEBUILD_SRC_DIR/product-photos/data
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - 1.Assign"    $CODEBUILD_SRC_DIR/product-photos/1.assign
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - 2.Message"   $CODEBUILD_SRC_DIR/product-photos/2.message
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - 2.Record"    $CODEBUILD_SRC_DIR/product-photos/2.record
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - 3.Receive"   $CODEBUILD_SRC_DIR/product-photos/3.receive
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - 4.Fail"      $CODEBUILD_SRC_DIR/product-photos/4.fail
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - 5.Unmessage" $CODEBUILD_SRC_DIR/product-photos/5.unmessage
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - 6.Report"    $CODEBUILD_SRC_DIR/product-photos/6.report
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - Process"     $CODEBUILD_SRC_DIR/product-photos/process       # deploy the StepFunction that depends on Lambdas 1-6
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - 0.Execute"   $CODEBUILD_SRC_DIR/product-photos/0.execute     # deploy the Lambda that listens to the stream and executes the StepFunction
