version: 0.1

phases:
  install:
    commands:
      - printenv
      - echo
      - node --version
      - npm --version
      #- npm install -g serverless
      - npm install -g git+https://github.com/erikerikson/serverless.git#allow-self-reference

      - sls --version
      - echo
      # Is this up to date?
      - aws s3 sync s3://com.$COMPANY.$TEAM.serverless.$REGION/secrets/hello-retail . --region $REGION
      - ls -l
      - head -50 ./private.yml
      - echo
  pre_build:
    commands:
      - chmod 700 $CODEBUILD_SRC_DIR/build/1.install.sh
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Top-Level Project Dependencies"           $CODEBUILD_SRC_DIR
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing New Product Simulator Dependencies"       $CODEBUILD_SRC_DIR/product-creation/lambda
      # Product Catalog
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Catalog Dependencies"             $CODEBUILD_SRC_DIR/product-catalog/builder
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Catalog API"                      $CODEBUILD_SRC_DIR/product-catalog/api
      # Product Photos
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Photos - Dispatch Dependencies"   $CODEBUILD_SRC_DIR/product-photos/1.dispatch
  build:
    commands:
      - npm run test
      - npm run lint
      - chmod 700 $CODEBUILD_SRC_DIR/build/2.deploy.sh
      # Core Stream
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Retail Stream"                $CODEBUILD_SRC_DIR/retail-stream
      # Product Creation
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying New Products Simulator"       $CODEBUILD_SRC_DIR/product-creation/lambda
      # Product Catalog
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Catalog Processor"    $CODEBUILD_SRC_DIR/product-catalog/builder
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Catalog API"          $CODEBUILD_SRC_DIR/product-catalog/api
      # Product Photos
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - Data"        $CODEBUILD_SRC_DIR/product-photos/0.data
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - Assign"      $CODEBUILD_SRC_DIR/product-photos/2.assign -step # deploy the step function that 1 starts and 3 stops (and thus depend on the exported arn of)
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - Dispatch"    $CODEBUILD_SRC_DIR/product-photos/1.dispatch
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Photos - Image"       $CODEBUILD_SRC_DIR/product-photos/3.image
