version: 0.1

phases:
  install:
    commands:
      - printenv
      - chmod 700 $CODEBUILD_SRC_DIR/build/0.env.sh
      - head -50 $CODEBUILD_SRC_DIR/build/0.env.sh
      - echo
      - node --version
      - npm --version
      - echo
      - npm install -g serverless
      - sls --version
      - echo
      # Is this up to date?
      - aws s3 sync s3://com.$COMPANY.$TEAM.serverless.$REGION/secrets/hello-retail . --region $REGION
      - ls -l
      - head -50 ./private.yml
      - echo
  pre_build:
    commands:
      - chmod 700 $CODEBUILD_SRC_DIR/build/1.install.sh
      - head -50 $CODEBUILD_SRC_DIR/build/1.install.sh
      - npm run root:install:all
  build:
    commands:
      - npm run test
      - npm run lint
      - chmod 700 $CODEBUILD_SRC_DIR/build/2.sls.sh
      - head -50 $CODEBUILD_SRC_DIR/build/2.sls.sh
      - npm run root:deploy:all
