version: 0.1

#environment_variables:
#  plaintext:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - pwd
      - npm install -g serverless
  pre_build:
    commands:
      - pwd
      - npm install
      - pwd
      - cd products/lambda
      - pwd
      - npm install
      - cd ../..
      - pwd
      - cd product-catalog
      - pwd
      - npm install
      - cd ..
      - pwd
  build:
    commands:
      - npm run test
      - npm run lint
#      - cd build
#      - sls deploy -s $STAGE
#      - cd ..
      - pwd
      - cd retail-stream
      - pwd
      - sls deploy -s $STAGE
      - cd ..
      - pwd
      - cd products/lambda
      - pwd
      - sls deploy -s $STAGE
      - cd ../..
      - pwd
      - cd product-catalog
      - pwd
      - sls deploy -s $STAGE
      - cd ..
      - pwd
  post_build:
    commands:
      # TODO acceptance tests
      # TODO (In a different project) integration tests
      # TODO (In a different project?) performance tests
#artifacts:
#  files:
#    - .travis.yml # a useless but small file to satisfy the buildspec.yml requirement
