version: 0.1

phases:
  install:
    commands:
      - printenv
      - echo
      - node --version
      - npm --version
      #- npm install -g serverless
      - npm install -g git+https://github.com/erikerikson/serverless.git#allow-self-reference

      - sls --version
      - echo
      # Is this up to date?
      - aws s3 sync s3://com.$COMPANY.$TEAM.serverless.$REGION/secrets/hello-retail . --region $REGION
      - ls -l
      - head -50 ./private.yml
      - echo
  pre_build:
    commands:
      - chmod 700 $CODEBUILD_SRC_DIR/build/1.install.sh
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Top-Level Project Dependencies"     $CODEBUILD_SRC_DIR
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing New Product Simulator Dependencies" $CODEBUILD_SRC_DIR/product-creation/lambda
      # Product Catalog
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Catalog Dependencies"       $CODEBUILD_SRC_DIR/product-catalog/builder
      - $CODEBUILD_SRC_DIR/build/1.install.sh "Installing Product Catalog API"                $CODEBUILD_SRC_DIR/product-catalog/api
  build:
    commands:
      - npm run test
      - npm run lint
      - chmod 700 $CODEBUILD_SRC_DIR/build/2.deploy.sh
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Retail Stream"              $CODEBUILD_SRC_DIR/retail-stream
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying New Products Simulator"     $CODEBUILD_SRC_DIR/product-creation/lambda
      # Product Catalog
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Catalog Processor"  $CODEBUILD_SRC_DIR/product-catalog/builder
      - $CODEBUILD_SRC_DIR/build/2.deploy.sh "Deploying Product Catalog API"        $CODEBUILD_SRC_DIR/product-catalog/api
