frameworkVersion: '>=1.0.0 <2.0.0'

service: ${self:custom.helloRetail.name}-${self:custom.productPhotos.name}-data

custom:
  stage: ${opt:stage, self:provider.stage, self:custom.private.stage}
  private: ${file(../private.yml)}
  helloRetail: ${file(../helloRetail.yml)}
  productPhotos: ${file(./productPhotos.yml)}

provider:
  name: aws
  deploymentBucket: com.${self:custom.private.company}.${self:custom.private.team}.serverless.${self:provider.region}
  runtime: nodejs4.3
  profile: ${self:custom.private.profile}
  region: ${self:custom.private.region}

resources:
  Resources:
    PhotoAssignments:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: product
            AttributeType: S
        KeySchema:
          - AttributeName: product
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: '${self:custom.stage}-PhotoAssignments-${self:custom.productPhotos.photoAssignmentsVersion}'
  Outputs:
    PhotoAssignmentsTableName:
      Description: The Name of the Photo Assignments Table
      Value:
        Ref: PhotoAssignments
      Export:
        Name: '${self:service}:${self:custom.stage}:PhotoAssignmentsTableName:${self:custom.productPhotos.photoAssignmentsVersion}'
    ProductCategoryTableArn:
      Description: The ARN for the Photo Assignments Table
      Value:
        'Fn::Join':
          - '/'
          - - 'arn:aws:dynamodb:${self:provider.region}:${self:custom.private.accountId}:table'
            - Ref: PhotoAssignments
      Export:
        Name: '${self:service}:${self:custom.stage}:PhotoAssignmentsTableArn:${self:custom.productPhotos.photoAssignmentsVersion}'
