frameworkVersion: '>=1.0.0 <2.0.0'

service: new-product-simulator # change to ${self:custom.helloRetail.name}-product-creation ???

custom:
  stage: ${opt:stage, self:provider.stage, self:custom.private.stage}
  private: ${file(../../private.yml)}
  helloRetail: ${file(../../helloRetail.yml)}
  retailStreamVersion: 1
  retailStream: ${file(../../retail-stream/serverless.yml)}

provider:
  name: aws
  deploymentBucket: ${self:custom.helloRetail.deploymentBucket}
  runtime: nodejs4.3
  profile: ${self:custom.private.profile}
  region: ${self:custom.private.region}

functions:
  scrapeProducts:
    handler: 'scrape-products/scrape-products.handler'
    environment:
      STAGE: ${self:custom.stage}
      STREAM_WRITER_ROLE:
        'Fn::ImportValue': ${self:custom.retailStream.custom.exportRetailStreamWriterArn}
      STREAM_NAME:
        'Fn::ImportValue': ${self:custom.retailStream.custom.exportRetailStreamName}
    role:
      Fn::GetAtt:
        - ProductStreamProducer
        - Arn

# you can add CloudFormation resource templates here
resources:
  Resources:
    ProductServiceLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: "/aws/lambda/${self:custom.stage}-${self:service}-newProductSimulator"
    ProductStreamProducer: # role for producing test products
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.stage}-${self:service}-newProductSimulator
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        ManagedPolicyArns:
          - ${self:custom.private.teamPolicy}
        Policies:
          - PolicyName: Logging
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                  Resource:
                    - Fn::GetAtt:
                      - ProductServiceLogGroup
                      - Arn
                - Effect: Allow
                  Action:
                    - logs:PutLogEvents
                  Resource:
                    - Fn::Join:
                      - ":"
                      - - Fn::GetAtt:
                          - ProductServiceLogGroup
                          - Arn
                        - "*"
