frameworkVersion: '>=1.0.0 <2.0.0'

service: hello-retail-website

custom:
  bucketArn:
    Fn::Join: # e.g. arn:aws:s3:::stage.hello-retail.biz/*
      - ''
      - - 'arn:aws:s3:::'
        - Ref: HelloRetailWebBucket
        - '/*'
  domainName: ${self:custom.private.domainName}
  dnsHostName:
    Fn::If: # e.g. hello-retail.biz or stage.hello-retail.biz
      - ProductionStage
      - ${self:custom.domainName}
      - ${self:custom.stage}.${self:custom.domainName}
  hostedZoneId: ${self:custom.private.hostedZoneId}
  originDomainName:
    Fn::Join: # e.g. hello-retail.biz.s3.amazonaws.com
      - ''
      - - ${self:custom.dnsHostName}
        - '.s3.amazonaws.com'
  originId:
    Fn::Join: # e.g. S3-hello-retail.biz or S3-stage.hello-retail.biz
      - ''
      - - 'S3-'
        - ${self:custom.dnsHostName}
  private: ${file(../private.yml)}
  stage: ${opt:stage, self:provider.stage, self:custom.private.stage}

provider:
  name: aws
  deploymentBucket: com.${self:custom.private.company}.${self:custom.private.team}.serverless.${self:provider.region}
  profile: ${self:custom.private.profile}
  region: ${self:custom.private.region}

resources:
  Conditions:
     ProductionStage:
       Fn::Equals:
         - ${self:custom.stage}
         - prod

  Resources:

    # ===================== S3 =====================

    HelloRetailWebBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.dnsHostName}
        # Really needed?
        CorsConfiguration:
          CorsRules:
          - AllowedHeaders: [Authorization]
            AllowedMethods: [GET]
            AllowedOrigins: [amazon.com]
            MaxAge: 3000
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html

    HelloRetailWebBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: HelloRetailWebBucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Resource: ${self:custom.bucketArn}
              Principal: '*'
      DependsOn:
        - HelloRetailWebBucket

    # ================ CloudFront ==================

    HelloRetailWebDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: ${self:custom.originId}
              DomainName: ${self:custom.originDomainName}
              S3OriginConfig:
                OriginAccessIdentity: ''
          Enabled: true
          DefaultRootObject: index.html
          # Really needed?
          Aliases:
          - Fn::If:
            - ProductionStage
            - hello-retail.biz
            - ${self:custom.stage}.hello-retail.biz
          DefaultCacheBehavior:
            AllowedMethods:
            - GET
            - HEAD
            TargetOriginId: ${self:custom.originId}
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            SslSupportMethod: sni-only
            AcmCertificateArn: ${self:custom.private.websiteSSLCert}
      DependsOn:
        - HelloRetailWebBucket

    # ================= Route 53 ===================

    HelloRetailWebRecordSetGroup:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId: ${self:custom.hostedZoneId}
        RecordSets:
        - Name: ${self:custom.dnsHostName}
          Type: A
          AliasTarget:
            DNSName: ${self:custom.originDomainName}
            HostedZoneId: ${self:custom.hostedZoneId}
        - Name: ${self:custom.dnsHostName}
          Type: AAAA
          AliasTarget:
            DNSName: ${self:custom.originDomainName}
            HostedZoneId: ${self:custom.hostedZoneId}
      DependsOn:
        - HelloRetailWebDistribution


#myDNS:
#  Type: AWS::Route53::RecordSetGroup
#  Properties:
#    HostedZoneId:
#      Ref: myHostedZoneID
#    RecordSets:
#    - Name:
#        Ref: myRecordSetDomainName
#      Type: A
#      AliasTarget:
#        HostedZoneId: Z2FDTNDATAQYW2
#        DNSName:
#          Ref: myCloudFrontDistributionDomainName
